set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
Plugin 'tpope/vim-sensible'
Plugin 'Shougo/neocomplcache.vim'
Plugin 'nathanaelkane/vim-indent-guides'
Plugin 'tpope/vim-surround'

call vundle#end()

filetype plugin indent on

syntax enable
set nu
set smartindent
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set background=dark
set showmatch
set hlsearch
set incsearch
set undolevels=1000
set autowrite
set showcmd

let mapleader = "\<Space>"
map <C-n> :cnext<CR>
map <C-m> :cprevious<CR>
nnoremap <leader>a :cclose<CR>

autocmd FileType python nmap <leader>r  :!python3 %<CR>
